spring.application.name=library

jwt.secret=5367566859703373367639792F423F452848284D6251655468576D5A71347437

# PostgreSQL connectiton
spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update